### ISSUE TITLE
Improved BOOM vs RC integration

### ISSUE THREAD

**Issue by tampler** [riscv-boom/riscv-boom#307]
Hello

We made a [fork](https://github.com/Neurodyne/boom) from your projects to maintain a production ready flows and have a sync with your development. 

You may reuse our build files to improve integration with the RC. The main improvement is to have an RC artifact inside the BOOM repo and use at least **compile** command to maintain a minimal coherence.

We'll maintain our own public copies of your repos for convenience. We also wanted to improve the response time on PRs and Issues.

I also performed an integration of the latest RC and BOOM code as per Jun 23 2019

Feel free to reuse our code.

Best,
Boris

**Comment by jerryz123** [comment]
We use our integrated development flow, which we update regularly and run regressions on.
The flow is available here https://github.com/ucb-bar/project-template/.
Keeping a submodule of rocketchip inside boom is not ideal, because there are external dependencies beyond rocketchip and boom which must be considered,

We will try to respond to PRs and issues quickly. PRs should pass the automated regressions first. We appreciate RC bumps, but we cannot merge those without bumping the rest of the components in our ecosystem, which takes time.
