### ISSUE TITLE
Superscalar decode broken by CSR decode

### ISSUE THREAD

**Issue by VaginAY** [riscv-boom/riscv-boom#37]
riscv-tests - last commit in master branch

Test commands:
   cd emulator
   make run CONFIG=MediumBoomConfig  // MegaBoomConfig still under understanding issue#35

Test combinations:
  Boom branch : none, use rocket core
  Rocket branch : master.
  Result: all good.

   Latest developement commit : 46aef9afae84fa3e4c908e33816734783e5bfee0
   Boom branch : devel
   Rocket branch : boom-devel.
   Result: endless execution on first test.

   Boom tag : v2.0.1
   Rocket branch : boom
   Result: fail on first test.

   Boom tag : v2.0
   Rocket branch : boom
   Result: fail on first test.

   Boom tag : v1.0
   Rocket branch : boom-v1
   Result: fail on first test.

  I think all riscv-tests must work for BOOM too, because ISA is similar for all cores.
  It's right? If so we will start debug with Cadence Incisive tomorrow, else please give
  your comments.

  Thanks. Best regards,
  Vagin Alexander

**Comment by ccelio** [comment]
There are two issues here.

First, you **must** use the riscv-tests that is found in `rocket-chip/riscv-tools/riscv-tests`. You can **not** use the master branch of riscv-tests. As one example, there was a privileged spec update from v2.0.1 to boom-devel so you must rebuild all of your riscv-tools on a BOOM update.

Second, on `devel` going forward, you **must** build a new compiler and specifically disable the Compressed Extension, since rv64imafdc is now the default compiler option. The `devel` readme describes how (https://github.com/ucb-bar/riscv-boom/blob/devel/README.md) under the "Installing the RISC-V Toolchain".

**Comment by VaginAY** [comment]
Thanks for fast reply. I'll try it this evening.

**Comment by VaginAY** [comment]
Latest developement commit : 3eb9560e93b6491cac9e4b1fc7fba499c02ba340
Boom branch : devel
Rocket branch : boom-devel.
Riscv-tools : commit from boom-devel branch of rocket without any checkouts,
compiled with --with-arch=rv64imafd.
Riscv-tests compile with recompiled riscv-tools.

Commands:
make run-bmark-tests CONFIG=MediumBoomConfig
make run-asm-tests CONFIG=MediumBoomConfig

Result: endless execution on tests
  benchmarks/mm.riscv
  rv64um-v-mul

I'll try v2.0.1 tag tomorrow (and may be v2.0 and v1.0, if it doesn't work).

**Comment by ccelio** [comment]
I have reproduced the error on my end.

**Working Config:**
SmallBoomConfig

**BrokenConfigs:**
BOOMConfig
MediumBoomConfig
SmallBoomConfig with fWidth=2

Looks like I dropped the ball on testing superscalar fetch somehow.

**Comment by ccelio** [comment]
Issue found. The method for detecting illegal instructions has changed -- decode bits are sent to the CSRFile and the CSRFile provides a Bundle of illegal signals (i.e., fp_illegal, system_illegal, etc.). 

However only one decode port is provided into the CSRFile. This breaks superscalar decode.

**Comment by ccelio** [comment]
Fixed. Requires pull of boom `devel` branch and rocket-chip `boom-devel` branch.
