### ISSUE TITLE
Global history register (ghr) in riscv-boom

### ISSUE THREAD

**Issue by hyf6661669** [riscv-boom/riscv-boom#424]
In br-predictor.scala:
```
/**
   * Hash input history with an address
   */
private def UpdateHistoryHash(old: UInt, addr: UInt): UInt = {
    val ret = Wire(UInt(historyLength.W))
    ret := DontCare
    // ret := ((addr >> 4.U) & 0xf.U) | (old << 4.U) -- for debugging
    val pc = addr >> log2Ceil(coreInstBytes)
    val foldpc = (pc >> 17) ^ pc
    val shamt = 2
    val sz0 = 6
    if (historyLength < (sz0*2+1)) {
      ret := (old << 1.U) ^ foldpc
    } else {
      val o0 = old(sz0-1,0)
      val o1 = old(2*sz0-1,sz0)

      val h0 = foldpc(sz0-1,0)
      val h1 = o0
      val h2 = (o1 ^ (o1 >> (sz0/2).U))(sz0/2-1,0)
      val min = h0.getWidth + h1.getWidth
      ret := Cat(old(historyLength-1, min), h2, h1, h0)
    }

    ret
  }
```
It seems that you don't use a shift register to implement ghr, but use a kind of hash function to calculate ghr. Could you give some explanation, thanks!

**Comment by jerryz123** [comment]
The old predictor used a shifted-path-history to index globally-indexed tables. For gshare a path history is sufficient, since the entire history is hashed with fetch-pc to index prediction structures. The structure of updating the global history is thus not important, as long as it in some form encapsulates the directions of the last-n branches.

We have a new-predictor with a taken/not-taken shifting global history tracking system, that will be released soon.
