### ISSUE TITLE
Will BOOM support vector extensions?

### ISSUE THREAD

**Issue by ghost** [riscv-boom/riscv-boom#473]
Vector extensions are extremely useful in modern processors so it would be a great idea to implement it. 

And I find that there are one uncompleted implementation. So will BOOM support vectors?

**Comment by jerryz123** [comment]
The old implementation approximately executed the v0.5 spec, but the current spec has evolved considerably since then. Ideally, eventually V-extension would be supported, but there is no one working on this right now.
In the meantime, BOOM can execute Hwacha vector extensions when coupled to the Hwacha vector accelerator.

**Comment by ghost** [comment]
Ok. Thanks for confirming.
