### ISSUE TITLE
Some questions about the Boom code

### ISSUE THREAD

**Issue by hz1490919302** [riscv-boom/riscv-boom#502]
1、In Lsu.Scala（line 1208）, the calculation in this code about store_blocked_counter seems to have a logical bug. Maybe instead of store_blocked_counter === 15.U, store_blocked_counter =/= 15.U?
![image](https://user-images.githubusercontent.com/27117133/99258726-f4d61700-2853-11eb-8d13-dc5d998253a1.png)

2、In Lsu.Scala（line 1220）,why is clr_unsafe (w).valid the value of which is always flase
![image](https://user-images.githubusercontent.com/27117133/99258941-3d8dd000-2854-11eb-8b18-57f78949ef37.png)

**Comment by jerryz123** [comment]
1. I believe this is correct?  This solves the problem when back-to-back loads saturate the LSU and block the store buffer from emptying. When that case is detected, loads are temporarily blocked. That is why the case is `store_blocked_counter === 15.U`

2. There are some bugs with aggressive clearing of the unsafe bit past speculative loads. Since the unsafe-bit only drives the PNR pointer, which doesn't drive anything performance-critical, aggressive load unsafe-clearing is disabled for now.
