### ISSUE TITLE
question about TAGE IUM

### ISSUE THREAD

**Issue by Lingrui98** [riscv-boom/riscv-boom#563]
**Type of issue**: bug report | feature request | question | other enhancement
question

Q: I noticed there was a commit b836971a2911fcd7c12b0eade84620b7df2b6f2c which removed IUM from TAGE and claimed that wrbypass was better. IUM is proposed to deal with the impact of delayed update, however a wrbypass does not seem to manage it. Is there any more evidence on that decision?

**Comment by jerryz123** [comment]
The issue I was attempting to solve at the time was the TAGE counters not being incremented properly in tightly looping code.
The IUM-solution fixed the counter value when it is read, while the wrbypass solution fixes the counter value when it is written.
While it is true that IUM addresses problems from delayed update in TAGE, it also caused some degenerate and confusing behavior, which is why I removed it.

**Comment by Lingrui98** [comment]
It seems that you implemented the IUM in TageTable, and store counters in IUM without updating it. I think that's why it caused the counter value problem. According to the original paper (and code), the IUM stores only the direction, and does not modify the predicted counters. Have you tried the original version of IUM?

**Comment by jerryz123** [comment]
Yeah now that you mention it, updating the IUM counters in the IUM directly would have been the better implementations.

**Comment by Lingrui98** [comment]
Thanks for your reply!
