### ISSUE TITLE
Why nResetLagCycles in BIM?

### ISSUE THREAD

**Issue by pentin-as** [riscv-boom/riscv-boom#85]
I'm modeling with $RANDOMIZE disabled.
I have the following error:
Assertion failed: Pipeline has hung.
    at core.scala: 1092 assert (! (idle_cycles.value (13)), "Pipeline has hung.")

This error occurs because bimDataArray reads 'XXXX'. This is due to the fact that bim_array is defined through the time nResetLagCycles, when part of the test is already running (see the figure below).

![screenshot from 2018-05-28 15-19-50](https://user-images.githubusercontent.com/30556064/40610986-0208e6f2-628e-11e8-8ae7-99f37791c0fd.png)
On the image:
 io_req, io_resp - icache
 bimDataArray, fsm_state - bim

I wanted to know, why nResetLagCycles is needed?

**Comment by et-ccelio** [comment]
Absent rigorous analysis, it's an attempt to prevent a power spike on reset with every RAM being reset on cycle 0.

This is absolutely a bug on the bim.io.resp and how it is consumed. The solution is to either zero the `bim.io.resp.bits` if `fsm_state =/= s_idle` or for the receiver to properly listen to `bim.io.resp.valid` instead of blindly consuming `bim.io.resp.bits` (in this case, the logic for `bim.io.resp.valid` is wrong). The former is easiest to implement (and safest since the consumer requires no/little modification), but I'm not sure if there is an FO4 argument to be made between the two.
